### ISSUE TITLE
qr code scan at launch versus install in sub directory

### ISSUE THREAD

**Issue by bidouilleur31** [mattjgalloway/emoncms-ios#1]
on ios 10.1B1 - iphone 7

launch -> use scan qr-code -> loads url but root level and not on sub level where emoncms is installed.
Api key is correctly read.
Push save
=> couldn't talk to emoncms. Are the credentials correct ?

**Comment by mattjgalloway** [comment]
This was fixed. Thanks @bidouilleur31!
